Envelope uses ES6 class
processing/p5.js-sound pull request #608
Opened 2021-04-25 16:07 UTC by Ajaya1000

changed to es6 class structure

2021-04-26 04:53 UTC, endurance21 requested changes

2021-04-26 04:53 UTC, endurance21 commented on src/envelope.js
> +    super();
pass the arguements of constructor to super() too.
We have a different aproach to handle the deprecations now.
please put this ENV to src/deprecations .

2021-04-26 04:56 UTC, endurance21 commented
@Ajaya1000  also check the examples if the p5.envelope is runnig fine https://github.com/processing/p5.js-sound/blob/main/examples/envelope/sketch.js
and let me know if everything is fine .
I wil verify and then we can merge this one

2021-04-26 07:28 UTC, Ajaya1000 commented
@endurance21 I have made the suggested changes and all examples using envelope classes are working as expected.

2021-04-26 09:46 UTC, endurance21 approved these changes

2022-12-30 17:04 UTC, Abhijay007 commented
Hi @Ajaya1000  can you please look into the merge conflicts, if you are busy I can resolve those conflicts and make a new PR  fixing merge conflicts around the same :)

2023-01-06 21:33 UTC, davepagurek commented
I'm going to close this for organizational purposes since the changes have been merged in as part of @Abhijay007's PR. Thanks for your changes @Ajaya1000!

2023-01-06 21:33 UTC, closed without merging